name: Release

on:
  push:
    tags: ['v*.*.*']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            artifact_name: zone-transfer-rs-macos-x86_64
          - target: aarch64-apple-darwin  
            artifact_name: zone-transfer-rs-macos-arm64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/zone-transfer-rs

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/zone-transfer-rs-macos-x86_64
            artifacts/zone-transfer-rs-macos-arm64
          draft: false
