name: Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Verify build output
        run: ls -la target/${{ matrix.target }}/release/
      
      - name: Package artifact
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/zone-transfer-rs release/
          tar -czvf release/${{ matrix.target }}.tar.gz -C release zone-transfer-rs
      
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: release/${{ matrix.target }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Extract artifacts
        run: |
          find artifacts -name '*.tar.gz' -exec tar -xzvf {} -C artifacts \;
      
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*/zone-transfer-rs
          draft: false
