name: Release

on:
  push:
    tags: ['v*.*.*']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            artifact_name: macos-x86_64
            output_name: zone-transfer-rs-x86_64-apple-darwin
          - target: aarch64-apple-darwin  
            artifact_name: macos-arm64
            output_name: zone-transfer-rs-aarch64-apple-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Prepare artifact
        run: |
          mkdir -p release/${{ matrix.artifact_name }}
          cp target/${{ matrix.target }}/release/zone-transfer-rs release/${{ matrix.artifact_name }}/${{ matrix.output_name }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: release/${{ matrix.artifact_name }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      
      - name: Rename assets
        run: |
          mkdir -p release_assets
          cp dist/macos-x86_64/zone-transfer-rs-x86_64-apple-darwin release_assets/
          cp dist/macos-arm64/zone-transfer-rs-aarch64-apple-darwin release_assets/
      
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            release_assets/*
          draft: false
